version: '3'
services:
  weather:
    build: 
      context: ./
      dockerfile: weather.dockerfile
    image: weather:1.0
    container_name: weather
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 50M

    # Ограничение по памяти
    #mem_limit: "256m"  # Ограничение по максимальной памяти
    #mem_reservation: "128m"  # Гарантированный минимальный объем памяти