version: '3.1'
services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    image: nginx:1.0
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/sites-available/nginx.conf
    depends_on:
      - weather

  weather:
    container_name: weather
    image: weather:1.0
    build: 
      context: ./
      dockerfile: weather.dockerfile
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 50M
